inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6.6
  Exclude:
    - "vendor/bundle/**/*"
    - "bin/*"
    - "db/**/*"
    - "tmp"
    - "lib"
    - "config/**/*"
    - "Gemfile"