inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6.6
  Exclude:
    - "vendor/bundle/**/*"
    - "bin/*"
    - "db/**/*"
    - "tmp/**/*"
    - "lib"
    - "config/**/*"
    - "Gemfile"

Rails:
  Enabled: true

Rails:/FilePath:
  Exclude:
    - 'lib/tasks/dev.rake'
    - 'spec/rails_helper.rb'

Style/AndOr:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false